---
deployment:
 tasks:
 - export DEPLOYPATH=/home/buggy/public_html/
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp -R img $DEPLOYPATH
 - /bin/cp -R scripts $DEPLOYPATH
 - /bin/cp -R styles $DEPLOYPATH
