---
deployment:
 tasks:
 - export DEPLOYPATH=/home/user/public_html/
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp img/247.jpg $DEPLOYPATH
 - /bin/cp scripts/bundle.js $DEPLOYPATH
 - /bin/cp styles/main.css $DEPLOYPATH